### ISSUE TITLE
Lab 02 - Lab Page

### ISSUE THREAD

**Issue by ecking** [DS4PS/cpp-529-spr-2020#3]
Hi there! 

So I just watched the video on the lab 2 and I feel like i'm missing the lab page you are referencing. I see the instructions in the rmd file, but thats a bit harder to read than directions on a webpage. 

Am I missing where that lab 2 directions are?

**Comment by nicolehillsmall** [comment]
@ecking I think this is how the instructions are presented for this lab - you could attempt to knit to a PDF or HTML so that you have something easier to reference

**Comment by AntJam-Howell** [comment]
Yes, you receive the raw code as .RMD file.  You hit the knit button to compile it into HTML output file, which will be easier to read.
